version: 2.1

jobs:
  test_llm_agent:
    docker:
      - image: cimg/python:3.10 # Use a stable Python image. Adjust version if needed.
    steps:
      - checkout

      - run:
          name: Install Python dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Run LLM Agent Tests
          command: |
            pytest tests/

      - store_test_results:
          path: test-results # Store test results for CircleCI's UI (requires JUnit XML output)
          # To generate JUnit XML, you might need to add: pytest --junitxml=test-results/junit.xml
          # to the pytest command if not configured via pytest.ini or setup.py

workflows:
  version: 2
  build_and_test_llm_agent:
    jobs:
      - test_llm_agent
